# type (r[1-9];w;u),circuit,name,[comment],[QQ],ZZ,PBSB,[ID],field1,part (m/s),datatypes/templates,divider/values,unit,comment
# I/O Test: heat pump,,,,,,,,,,,,,
*wi,#install,,,,,"B506",,,,,,,
wi,,iotest,I/O test,,,,02,,,UCH,0=off;1=coolvalve;2=sourcepump;3=hcpump;4=injector;5=caseheater;6=backup;7=hwchcvalve;8=cirpump;9=sc2pump;10=hc2pump;11=hc2mixeropen;12=hc2mixerclose,,
wi,,ioteststop,stop I/O test,,,,01,,,,,,
