# type (r[1-9];w;u),circuit,name,[comment],[QQ],ZZ,PBSB,[ID],field1,part (m/s),datatypes/templates,divider/values,unit,comment
# yield,,,,,,,,,,,,,
*r,,,,,,"B509","0D",,,,,,
r9,,YieldThisYear,yield this year,,,,"3f00:2;3f08:2;3f10:2;3f18:2;3f20:2;3f28:2;3f30:2;3f38:2;3f40:2;3f48:2;3f50:2;3f58:2",,,energy;energy;energy;energy;energy;energy;energy;energy;energy;energy;energy;energy,,,
r,,YieldLastYear,yield last year,,,,"4000:2;4008:2;4010:2;4018:2;4020:2;4028:2;4030:2;4038:2;4040:2;4048:2;4050:2;4058:2",,,energy;energy;energy;energy;energy;energy;energy;energy;energy;energy;energy;energy,,,
