# type (r[1-9];w;u),circuit,name,[comment],[QQ],ZZ,PBSB,[ID],field1,part (m/s),datatypes/templates,divider/values,unit,comment
# I/O test: 620,,,,,,,,,,,,,
*wi,#install,,,,,"B506",,,,,,,
wi,,iotest,I/O test,,,,02,,,UCH,0=valve1;1=cirpump;2=pump1;3=hc2mixeropen;4=hc2mixerclose;5=hc2pump;6=col1pump;7=col2pump;8=valve2;9=valve3;10=legiopump;11=valve4;12=c1c2,,
wi,,ioteststop,stop I/O test,,,,01,,,,,,
