# type (r[1-9];w;u),circuit,name,[comment],[QQ],ZZ,PBSB,[ID],field1,part (m/s),datatypes/templates,divider/values,unit,comment
# I/O test: 630,,,,,,,,,,,,,
*wi,#install,,,,,"B506",,,,,,,
wi,,iotest,I/O test,,,,02,,,UCH,0=valve1;1=cirpump;2=pump1;3=hc2mixeropen;4=hc2mixerclose;5=hc2pump;6=hc3mixeropen;7=hc3mixerclose;8=hc3pump;9=level1;10=level2;11=av;12=c1c2,,
wi,,ioteststop,stop I/O test,,,,01,,,,,,
