# type (r[1-9];w;u),circuit,name,[comment],[QQ],ZZ,PBSB,[ID],field1,part (m/s),datatypes/templates,divider/values,unit,comment
# MC: Operation mode,,,,,,,,,,,,,
*r,,,,,,"B504",,,,,,,
r,,Mode,Operation mode,,,,01,,,temp0;mcmode;IGN:2;HEX;IGN;onoff;IGN,,,
r,,DateTime,Date Time,,,,00,,,dcfstate;btime;bdate;temp2,,,
r,,Status,Status,,,,0D,,,temp0;onoff;temp;temp0,,,
r,,Status16,Outsidetemperature,,,,16,,,temp,,,
