# type (r[1-9];w;u),circuit,name,[comment],[QQ],ZZ,PBSB,[ID],field1,part (m/s),datatypes/templates,divider/values,unit,comment
# Setpoints temperature
*r,,,,,,"B504","19",,,IGN:1,,,
*w,,,,,,"B505","2e",,,,,,
r;w,,Setpoints.Monday,Temperatures Monday,,,,01,,,temp1;temp1;temp1,,,
r;w,,Setpoints.Tuesday,Temperatures Tuesday,,,,02,,,temp1;temp1;temp1,,,
r;w,,Setpoints.Wednesday,Temperatures Wednesday,,,,03,,,temp1;temp1;temp1,,,
r;w,,Setpoints.Thursday,Temperatures Thursday,,,,04,,,temp1;temp1;temp1,,,
r;w,,Setpoints.Friday,Temperatures Friday,,,,05,,,temp1;temp1;temp1,,,
r;w,,Setpoints.Saturday,Temperatures Saturday,,,,06,,,temp1;temp1;temp1,,,
r;w,,Setpoints.Sunday,Temperatures Sunday,,,,07,,,temp1;temp1;temp1,,,
