# type (r[1-9];w;u),circuit,name,[comment],[QQ],ZZ,PBSB,[ID],field1,part (m/s),datatypes/templates,divider/values,unit,comment
# yield,,,,,,,,,,,,,
*r,,,,,,"B509","0D",,,,,,
r9,,YieldThisYear,yield this year,,,,"8400:2;8408:2;8410:2;8418:2;8420:2;8428:2;8430:2;8438:2;8440:2;8448:2;8450:2;8458:2",,,energy;energy;energy;energy;energy;energy;energy;energy;energy;energy;energy;energy,,,
r,,YieldLastYear,yield last year,,,,"8500:2;8508:2;8510:2;8518:2;8520:2;8528:2;8530:2;8538:2;8540:2;8548:2;8550:2;8558:2",,,energy;energy;energy;energy;energy;energy;energy;energy;energy;energy;energy;energy,,,
