# type (r[1-9];w;u),circuit,name,[comment],[QQ],ZZ,PBSB,[ID],field1,part (m/s),datatypes/templates,divider/values,unit,comment
# yield,,,,,,,,,,,,,
*r,,,,,,"B509","0D",,,,,,
r9,,YieldThisYear,yield this year,,,,"4400:2;4408:2;4410:2;4418:2;4420:2;4428:2;4430:2;4438:2;4440:2;4448:2;4450:2;4458:2",,,energy;energy;energy;energy;energy;energy;energy;energy;energy;energy;energy;energy,,,
r,,YieldLastYear,yield last year,,,,"4500:2;4508:2;4510:2;4518:2;4520:2;4528:2;4530:2;4538:2;4540:2;4548:2;4550:2;4558:2",,,energy;energy;energy;energy;energy;energy;energy;energy;energy;energy;energy;energy,,,
