# type (r[1-9];w;u),circuit,name,[comment],[QQ],ZZ,PBSB,[ID],field1,part (m/s),datatypes/templates,divider/values,unit,comment,field2,part (m/s),datatypes/templates,divider/values,unit,comment,field3,part (m/s),datatypes/templates,divider/values,unit,comment,field4,part (m/s),datatypes/templates,divider/values,unit,comment
*r,emm,,,,08,"B524","02000000"
r,,Unknown35,,,,,"0100"
r,,Unknown36,,,,,"0200"
r,,Unknown1,,,,,"0400"
r,,Unknown2,,,,,"0A00"
r,,Unknown37,,,,,"0F00"
r,,Unknown38,,,,,"1300"
r,,Unknown39,,,,,"1400"
r,,Unknown40,,,,,"1700"
r,,Unknown41,,,,,"2200"
r,,Unknown42,,,,,"2300"
r,,Unknown43,,,,,"2400"
r,,Unknown44,,,,,"2600"
r,,Unknown45,,,,,"2700"
r,,Unknown46,,,,,"2900"
r,,Unknown34,,,,,"2B00",,,IGN:4,,,,,,HEX:*,,,
r,,Unknown47,,,,,"2F00"
r,,Unknown48,,,,,"3600"
r,,Unknown69,,,,,"4500"
r,,Unknown49,,,,,"4600"
r,,Unknown3,,,,,"4800",,,IGN:4,,,,,,HEX:*,,,
r,,Unknown4,,,,,"4B00",,,IGN:4,,,,,,HEX:*,,,
r,,Unknown50,,,,,"9500"
r,,Unknown6,,,,,"9D00"
r,,Unknown7,,,,,"9E00"
r,,Unknown8,,,,,"9F00"
r,,Unknown9,,,,,"A000"
r,,Unknown10,,,,,"A200",,,IGN:4,,,,,,EXP,,,
r,,Unknown51,,,,,"B500",,,IGN:4,,,,,,HEX:*,,,
r,,Unknown11,,,,,"B600",,,IGN:4,,,,,,HEX:*,,,
r,,Unknown52,,,,,"da00",,,IGN:4,,,,,,HDA:3,,,
r,,Unknown53,,,,,"db00",,,IGN:4,,,,,,HDA:3,,,
r,,Unknown54,,,,,"EF00",,,IGN:4,,,,,,EXP,,,
r,,Unknown12,,,,,"F200",,,IGN:4,,,,,,HDA:3,,,
r,,Unknown13,,,,,"F300",,,IGN:4,,,,,,HDA:3,,,
r,,Unknown14,,,,,"F400",,,IGN:4,,,,,,HEX:*,,,
r,,Unknown15,,,,,"F500",,,IGN:4,,,,,,HEX:*,,,
r,,Unknown17,,,,,"F700",,,IGN:4,,,,,,HEX:*,,,
r,,Unknown18,,,,,"F900",,,IGN:4,,,,,,HEX:*,,,

*r,emm,,,,08,"B524","02000100"
r,,Unknown66,,,,,"0100",,,IGN:4,,,,,,HEX:*,,,
r,,Unknown19,,,,,"0F00",,,IGN:4,,,,,,HEX:*,,,

*r,emm,,,,08,"B524","02000200"
r,,Unknown67,,,,,"0100",,,IGN:4,,,,,,HEX:*,,,
r,,Unknown20,,,,,"0200",,,IGN:4,,,,,,HEX:*,,,
r,,Unknown21,,,,,"0600",,,IGN:4,,,,,,HEX:*,,,
r,,Unknown55,,,,,"0700",,,IGN:4,,,,,,HEX:*,,,
r,,Unknown22,,,,,"0800",,,IGN:4,,,,,,HEX:*,,,
r,,Unknown56,,,,,"0b00"
r,,Unknown23,,,,,"0E00",,,IGN:4,,,,,,HEX:*,,,
r,,Unknown57,,,,,"0F00",,,IGN:4,,,,,,EXP,,,
r,,Unknown58,,,,,"1000",,,IGN:4,,,,,,EXP,,,
r,,Unknown59,,,,,"1200",,,IGN:4,,,,,,EXP,,,
r,,Unknown60,,,,,"1400",,,IGN:4,,,,,,HEX:*,,,
r,,Unknown33,,,,,"1500",,,IGN:4,,,,,,HEX:*,,,
r,,Unknown24,,,,,"1E00",,,IGN:4,,,,,,HEX:*,,,

*r,emm,,,,08,"B524","02000300"
r,,Unknown25,,,,,"0500",,,IGN:4,,,,,,EXP,,,
r,,Unknown26,,,,,"0F00",,,IGN:4,,,,,,HEX:*,,,
r,,Unknown27,,,,,"1100",,,IGN:4,,,,,,HEX:*,,,
r,,Unknown86,,,,,"1300",,,IGN:4,,,,,,HEX:*,,,
r,,Unknown28,,,,,"1B00",,,IGN:4,,,,,,HEX:*,,,
r,,Unknown29,,,,,"1C00",,,IGN:4,,,,,,HEX:*,,,
r,,Unknown32,,,,,"2800",,,IGN:4,,,,,,HEX:*,,,

*r,emm,,,,08,"B524",,,,,,,
r,,Unknown68,,,,,"020002020200"
r,,Unknown70,,,,,"020003021c00"
*r,emm,,,,08,"B524",,,,,,,
r,,Unknown71,,,,,"020002030200"
r,,Unknown72,,,,,"020003031c00"
*r,emm,,,,08,"B524",,,,,,,
r,,Unknown73,,,,,"020002010200"
r,,Unknown74,,,,,"020003011c00"
*r,emm,,,,08,"B524",,,,,,,
r,,Unknown75,,,,,"020002060200"
r,,Unknown76,,,,,"020003061c00"
*r,emm,,,,08,"B524",02000207,,,,,,
r,,Unknown77,,,,,"020002070200"
r,,Unknown78,,,,,"020003071c00"
*r,emm,,,,08,"B524",,,,,,,
r,,Unknown79,,,,,"020002040200"
r,,Unknown80,,,,,"020003041c00"
*r,emm,,,,08,"B524",,,,,,,
r,,Unknown81,,,,,"020002050200"
r,,Unknown82,,,,,"020003051c00"
*r,emm,,,,08,"B524",,,,,,,
r,,Unknown83,,,,,"020002080200"
r,,Unknown84,,,,,"020003081c00"

*r,emm,,,,08,"B516",1000ffff,,,,,,
r,,Unknown61,,,,,"42030000",,,IGN:7,,,,,,ULG,,Wh, Bedeutung des Absolutwertes unklar;
r,,Unknown62,,,,,"42040000",,,IGN:7,,,,,,ULG,,Wh, Bedeutung des Absolutwertes unklar;
r,,Unknown63,,,,,"42050000",,,IGN:7,,,,,,ULG,,Wh, Bedeutung des Absolutwertes unklar;
r,,Unknown64,,,,,"01000000",,,IGN:7,,,,,,ULG,,Wh, Bedeutung des Absolutwertes unklar;
r,,Unknown85,,,15,,"01000000",,,IGN:7,,,,,,ULG,,Wh, Bedeutung des Absolutwertes unklar;
r,,Unknown65,,,,,"41030000",,,IGN:7,,,,,,ULG,,Wh, Bedeutung des Absolutwertes unklar;
r,,ConsumedElectricalEnergyOfSomething,Verbrauch elektrischer Energie von ? (vielleicht Wärmepumpe),,,,"83050000",,,IGN:7,,,,,,ULG,,Wh, Bedeutung des Absolutwertes unklar;
r,,HeatGeneratedOfSomething,Erzeugte Wärme von ? (vielleicht Wärmepumpe),,,,"49050000",,,IGN:7,,,,,,ULG,,Wh, Bedeutung des Absolutwertes unklar;
