# type (r[1-9];w;u),circuit,name,[comment],[QQ],ZZ,PBSB,[ID],field1,part (m/s),datatypes/templates,divider/values,unit,comment,field2,part (m/s),datatypes/templates
# MK1: Betriebsart,,,,,,,,,,,,,
*r,,,,,,"B504",,,,,,,
r,,Mode,Betriebsart,,,,01,,,temp0;mcmode;IGN:2;HEX;IGN;onoff;IGN,,,
r,,DateTime,Datum Uhrzeit,,,,00,,,dcfstate;btime;bdate;temp2,,,
r,,Status,Status,,,,0D,,,temp0;onoff;temp;temp0,,,
r,,Status16,Aussentemperatur,,,,16,,,temp,,,
