# type (r[1-9];w;u),circuit,name,[comment],[QQ],ZZ,PBSB,[ID],field1,part (m/s),datatypes/templates,divider/values,unit,comment
# Zeitprogramme Temperatur
*r,,,,,,"B504","19",,,IGN:1,,,
*w,,,,,,"B505","2e",,,,,,
r;w,,Setpoints.Monday,Temperaturen Montag,,,,01,,,temp1;temp1;temp1,,,
r;w,,Setpoints.Tuesday,Temperaturen Dienstag,,,,02,,,temp1;temp1;temp1,,,
r;w,,Setpoints.Wednesday,Temperaturen Mittwoch,,,,03,,,temp1;temp1;temp1,,,
r;w,,Setpoints.Thursday,Temperaturen Donnerstag,,,,04,,,temp1;temp1;temp1,,,
r;w,,Setpoints.Friday,Temperaturen Freitag,,,,05,,,temp1;temp1;temp1,,,
r;w,,Setpoints.Saturday,Temperaturen Samstag,,,,06,,,temp1;temp1;temp1,,,
r;w,,Setpoints.Sunday,Temperaturen Sonntag,,,,07,,,temp1;temp1;temp1,,,
