# type (r[1-9];w;u),circuit,name,[comment],[QQ],ZZ,PBSB,[ID],field1,part (m/s),datatypes/templates,divider/values,unit,comment
#Zeitprogramme Temperatur
*r,,,,,,"B504","19",,,,,,
*w,,,,,,"B505","2e01",,,,,,
r;w,,Setpoints.Monday,Temperatur Montag,,,,01,,,temp1;temp1;temp1,,,
r;w,,Setpoints.Tuesday,Temperatur Dienstag,,,,02,,,temp1;temp1;temp1,,,
r;w,,Setpoints.Wednesday,Temperatur Mittwoch,,,,03,,,temp1;temp1;temp1,,,
r;w,,Setpoints.Thursday,Temperatur Donnerstag,,,,04,,,temp1;temp1;temp1,,,
r;w,,Setpoints.Friday,Temperatur Freitag,,,,05,,,temp1;temp1;temp1,,,
r;w,,Setpoints.Saturday,Temperatur Samstag,,,,06,,,temp1;temp1;temp1,,,
r;w,,Setpoints.Sunday,Temperatur Sonntag,,,,07,,,temp1;temp1;temp1,,,
