# type (r[1-9];w;u),circuit,name,[comment],[QQ],ZZ,PBSB,[ID],field1,part (m/s),datatypes/templates,divider/values,unit,comment
# yield,,,,,,,,,,,,,
*r,,,,,,"B509","0D",,,,,,
r9,,YieldThisYear,Ertrag dieses Jahr,,,,"3d00:2;3d08:2;3d10:2;3d18:2;3d20:2;3d28:2;3d30:2;3d38:2;3d40:2;3d48:2;3d50:2;3d58:2",,,energy;energy;energy;energy;energy;energy;energy;energy;energy;energy;energy;energy,,,
r,,YieldLastYear,Ertrag letztes Jahr,,,,"4300:2;4308:2;4310:2;4318:2;4320:2;4328:2;4330:2;4338:2;4340:2;4348:2;4350:2;4358:2",,,energy;energy;energy;energy;energy;energy;energy;energy;energy;energy;energy;energy,,,
