name: Generate csv configuration files.

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 1
          submodules: true
      - name: Use Node.js node 20.x
        uses: actions/setup-node@v6
        with:
          node-version: 20.x
      - name: Install packages
        run: npm install -omit=dev
        working-directory: ./
      - name: Convert typespec files (en+de+cs)
        run: ./utils/precheck.sh
        working-directory: ./
      - name: Zobraz aktuální adresář
        run: pwd

      - name: Vylistuj soubory (rekurzivně)
        run: ls -ltra

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: conversion_result
          path: ./utils/outcsv/
